version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Install dependencies..."
      - npm ci
      - npm install

  build:
    commands:
      - echo "Run playwright test..."
      - npm run test

artifacts:
  files:
    - storageState.json
    - test-results/**/*

cache:
  paths:
    - node_modules/**/*
